### ISSUE TITLE
RuntimeError: mat1 and mat2 must have the same dtype, but got Float and Half

### ISSUE THREAD

**Issue by renatz** [weiyifan1023/Neeko#6]
brilliant job!

I have adapted it to llama-2-7b, but when I utilized qwen-1.5 as bakcbone, something wrong as below:

```
wandb: \U0001f680 View run at https://wandb.ai/renatz1224/rpa/runs/5fmxogau                                           ddp_find_unused_parameters needs to be set as False in DDP training.                                                
[INFO|training_args.py:2120] 2024-10-08 18:53:53,431 >> PyTorch: setting up devices                                   
[INFO|training_args.py:1808] 2024-10-08 18:53:53,465 >> The default value for the training argument --report_to will
 change in v5 (from all installed integrations to none). In v5, you will need to use --report_to all to get the same
 behavior as now. You should start updating your code and make this info disappear :-).                               
ddp_find_unused_parameters needs to be set as False in DDP training.                                                
[INFO|tokenization_utils_base.py:2212] 2024-10-08 18:53:53,475 >> loading file vocab.json                             
[INFO|tokenization_utils_base.py:2212] 2024-10-08 18:53:53,476 >> loading file merges.txt                             
[INFO|tokenization_utils_base.py:2212] 2024-10-08 18:53:53,476 >> loading file added_tokens.json                      
[INFO|tokenization_utils_base.py:2212] 2024-10-08 18:53:53,476 >> loading file special_tokens_map.json                
[INFO|tokenization_utils_base.py:2212] 2024-10-08 18:53:53,476 >> loading file tokenizer_config.json                  
[INFO|tokenization_utils_base.py:2212] 2024-10-08 18:53:53,476 >> loading file tokenizer.json                         
[INFO|tokenization_utils_base.py:2478] 2024-10-08 18:53:53,709 >> Special tokens have been added in the vocabulary, ma
ke sure the associated word embeddings are fine-tuned or trained.                                                     
[INFO|configuration_utils.py:670] 2024-10-08 18:53:53,711 >> loading configuration file /home/comp/cscykong/persona/mo
del/download/Qwen/Qwen1.5-7B/config.json                        

[INFO|configuration_utils.py:739] 2024-10-08 18:53:53,715 >> Model config Qwen2Config {                               
  "_name_or_path": "/home/comp/cscykong/persona/model/download/Qwen/Qwen1.5-7B",                                      
  "architectures": [                                                                                                  
    "Qwen2ForCausalLM"                                                                                                
  ],                                                                                                                  
  "attention_dropout": 0.0,                                                                                           
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.45.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

[INFO|modeling_utils.py:3723] 2024-10-08 18:53:53,810 >> loading weights file /home/comp/cscykong/persona/model/downlo
ad/Qwen/Qwen1.5-7B/model.safetensors.index.json
[INFO|modeling_utils.py:1622] 2024-10-08 18:53:53,811 >> Instantiating Qwen2ForCausalLM model under default dtype torc
h.float16.
[INFO|configuration_utils.py:1099] 2024-10-08 18:53:53,813 >> Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643
}

Loading checkpoint shards: 100%|########################################################| 4/4 [00:16<00:00,  4.09s/it]
[INFO|modeling_utils.py:4568] 2024-10-08 18:54:10,271 >> All model checkpoint weights were used when initializing Qwen
2ForCausalLM.

[INFO|modeling_utils.py:4576] 2024-10-08 18:54:10,271 >> All the weights of Qwen2ForCausalLM were initialized from the
 model checkpoint at /home/comp/cscykong/persona/model/download/Qwen/Qwen1.5-7B.
If your task is similar to the task the model of the checkpoint was trained on, you can already use Qwen2ForCausalLM f
or predictions without further training.
[INFO|configuration_utils.py:1052] 2024-10-08 18:54:10,278 >> loading configuration file /home/comp/cscykong/persona/m
odel/download/Qwen/Qwen1.5-7B/generation_config.json
[INFO|configuration_utils.py:1099] 2024-10-08 18:54:10,279 >> Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

trainable params: 17301504 || all params: 7738626048 || trainable%: 0.2236
Spawning 32 processes
Running tokenizer on dataset (num_proc=32): 100%|#######################| 14174/14174 [01:27<00:00, 161.91 examples/s]
Concatenating 32 shards
input_ids:

[None, 40, 1366, 498, 311, 1160, 1075, 53499, 2825, 4003, 13, 358, 1366, 498, 311, 5889, 323, 4226, 1075, 53499, 2825,
 4003, 11, 1667, 279, 16232, 11, 11566, 323, 34918, 53499, 2825, 4003, 1035, 990, 13, 1446, 1969, 1414, 678, 315, 279,
 6540, 315, 53499, 2825, 4003, 13, 4710, 785, 2639, 315, 498, 374, 438, 11017, 510, 4707, 25, 77153, 198, 2522, 25, 53
499, 2825, 4003, 11, 264, 23074, 3908, 36382, 74012, 77153, 6022, 315, 38350, 7712, 323, 38387, 884, 13, 2932, 374, 38
81, 369, 1059, 24364, 23702, 17541, 323, 7361, 323, 374, 6509, 264, 88514, 34101, 553, 1059, 25029, 323, 44624, 13, 75
8, 419, 6109, 11, 53499, 374, 16634, 304, 264, 11004, 448, 825, 315, 1059, 44624, 916, 279, 1850, 1616, 311, 5358, 264
, 23702, 17218, 504, 14381, 11428, 13, 576, 6243, 374, 77153, 11, 323, 279, 882, 374, 2337, 825, 315, 53499, 594, 6846
, 382, 785, 21880, 525, 438, 11017, 1447, 39, 4195, 6339, 320, 82260, 1648, 220, None, 40, 646, 944, 4411, 279, 14227,
 374, 22561, 1741, 264, 53390, 292, 1714, 311, 5358, 279, 23702, 17218, 504, 14381, 11428, 13, 2619, 702, 311, 387, 26
4, 2664, 1616, 13, 358, 1184, 311, 1744, 315, 264, 1616, 311, 26910, 1435, 429, 1052, 374, 264, 803, 81026, 6291, 13,
151643, 47020, 320, 33374, 1765, 1648, 358, 3535, 429, 498, 614, 10520, 11, 8906, 2825, 4003, 11, 714, 7025, 14226, 10
953, 525, 5871, 311, 5358, 11428, 13, 1205, 4157, 1896, 894, 16963, 448, 11406, 23702, 19970, 13, 39, 4195, 6339, 320,
 33374, 1765, 1648, 220, None, 3983, 11, 16642, 11, 1052, 702, 311, 387, 264, 2664, 1616, 13, 1205, 646, 944, 1101, 21
788, 311, 13118, 1493, 19970, 2041, 4460, 311, 1477, 264, 803, 81026, 6291, 13, 3555, 421, 582, 1483, 264, 12845, 311,
 7557, 1105, 311, 264, 803, 14452, 4573, 1380, 807, 2765, 944, 17040, 264, 7978, 311, 3800, 30, 151643, 47020, 320, 33
374, 1765, 1648, 2938, 374, 264, 13038, 11, 8906, 2825, 4003, 11, 714, 582, 614, 6679, 429, 304, 279, 3267, 11, 323, 4
32, 702, 537, 1012, 6849, 13, 4220, 19970, 525, 2238, 11406, 323, 49135, 11, 323, 582, 4157, 5214, 279, 7149, 315, 103
9, 4143, 323, 21564, 13, 39, 4195, 6339, 320, 82260, 1648, 220, None, 40, 1184, 311, 2525, 705, 448, 264, 803, 65243,
5693, 13, 10696, 421, 358, 10339, 279, 15917, 315, 13118, 1493, 19970, 323, 279, 5421, 432, 1410, 614, 389, 279, 23702
, 24982, 11, 566, 686, 1490, 2874, 13, 151643, 39, 4195, 6339, 320, 33374, 1765, 1648, 220, None, 3983, 11, 16642, 11,
 13118, 1493, 19970, 1410, 614, 13207, 15917, 13, 2379, 525, 264, 16198, 949, 315, 279, 23702, 24982, 11, 323, 862, 47
09, 1410, 614, 264, 69625, 2456, 389, 1008, 23702, 19970, 323, 10779, 13, 1205, 614, 264, 11752, 311, 6016, 323, 21129
, 279, 23702, 1879, 11, 537, 1101, 1896, 279, 4135, 1616, 700, 13, 151643, 47020, 320, 33374, 1765, 1648, 358, 3535, 6
97, 10520, 11, 8906, 2825, 4003, 11, 714, 582, 4157, 1896, 894, 16963, 13, 576, 7149, 315, 1039, 4143, 323, 21564, 374
, 1039, 1909, 10619, 13, 39, 4195, 6339, 320, 82260, 1648, 220, None, 40, 1184, 311, 1744, 315, 264, 2664, 5693, 13, 1
0696, 421, 358, 14303, 311, 806, 5530, 315, 44551, 323, 30908, 11, 566, 686, 1490, 2874, 13, 151643, 39, 4195, 6339, 3
20, 33374, 1765, 1648, 220, None, 47020, 11, 358, 3163, 20156, 498, 311, 39075, 13, 576, 23702, 1879, 374, 537, 1101,
911, 2355, 323, 2524, 13, 1084, 594, 911, 29381, 323, 47351, 13, 1205, 614, 264, 11752, 311, 678, 19970, 11, 23702, 47
6, 5937, 11, 311, 4228, 1105, 448, 37829, 323, 5091, 13, 1205, 4157, 1101, 1896, 862, 6305, 2041, 4460, 311, 1477, 264
, 803, 81026, 6291, 13, 151643, 47020, 320, 33374, 1765, 1648, 358, 15401, 697, 11303, 11, 8906, 2825, 4003, 11, 714,
7025, 582, 614, 311, 1281, 11045, 11181, 13, 358, 686, 1896, 697, 18225, 1119, 17879, 11, 714, 369, 1431, 11, 582, 686
, 614, 311, 21788, 311, 279, 1429, 7373, 1714, 315, 26160, 11428, 13, 39, 4195, 6339, 320, 82260, 1648, 220, None, 40,
 646, 944, 4411, 566, 2765, 944, 8844, 311, 2874, 13, 358, 1184, 311, 1477, 264, 1616, 311, 26910, 1435, 1573, 432, 59
4, 2238, 3309, 13, 151643, 39, 4195, 6339, 320, 33374, 1765, 1648, 220, None, 47020, 11, 4486, 11, 358, 2148, 315, 498
, 311, 39075, 13, 2619, 702, 311, 387, 264, 2664, 1616, 13, 1205, 4157, 1101, 21788, 311, 13118, 1493, 19970, 2041, 44
60, 311, 1477, 264, 803, 81026, 6291, 13, 358, 1079, 9831, 311, 975, 448, 498, 311, 1477, 264, 2664, 1616, 311, 5978,
279, 7149, 315, 1039, 4143, 323, 21564, 13, 151643, 47020, 320, 33374, 1765, 1648, 358, 15401, 697, 38855, 11, 8906, 2
825, 4003, 11, 714, 7025, 582, 614, 311, 1281, 11045, 11181, 13, 358, 686, 1896, 697, 18225, 1119, 17879, 11, 714, 369
, 1431, 11, 582, 686, 614, 311, 990, 279, 1429, 7373, 1714, 315, 26160, 11428, 13, 39, 4195, 6339, 320, 82260, 1648, 2
20, None, 40, 646, 944, 4411, 566, 2765, 944, 1496, 2908, 847, 18225, 13, 358, 1184, 311, 1477, 264, 1616, 311, 26910,
 1435, 1573, 432, 594, 2238, 3309, 13, 10696, 421, 358, 3412, 803, 911, 419, 17218, 323, 1477, 264, 2664, 6291, 11, 56
6, 686, 8844, 311, 2874, 13, 151643]
Traceback (most recent call last):
  File "/home/comp/cscykong/persona/Neeko/train.py", line 18, in <module>
    trainer = LLaMaTrainer([datasets], template)
File "/home/comp/cscykong/persona/Neeko/src/trainer.py", line 25, in __init__
    self.dataset = preprocess_data(template, self.dataset, self.tokenizer, self.data_args, self.training_args)
  File "/home/comp/cscykong/persona/Neeko/src/dataset.py", line 101, in preprocess_data
    print_supervised_dataset_example(dataset[0])
  File "/home/comp/cscykong/persona/Neeko/src/dataset.py", line 82, in print_supervised_dataset_example
    print("inputs:\n{}".format(tokenizer.decode(example["input_ids"], skip_special_tokens=False)))
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/models/qwen2/tokenization_qw
en2.py", line 299, in decode
    return super().decode(
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/tokenization_utils_base.py",
 line 4007, in decode
    return self._decode(
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/tokenization_utils.py", line
 1088, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/tokenization_utils.py", line
 1063, in convert_ids_to_tokens
    index = int(index)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

the script is shown below:
```
python train.py \
    --model_name_or_path /home/comp/cscykong/persona/model/download/Qwen/Qwen1.5-7B \
    --data_path /home/comp/cscykong/persona/corpus/character-llm-data/prompted/shuffle.jsonl \
    --embds_dir /home/comp/cscykong/persona/Neeko/role_embds \
    --do_train \
    --finetuning_type moelora \
    --output_dir ./ckpt/neeko/$current_time/ \
    --num_hidden_layers 32 \
    --max_source_length 4096 \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 2e-4 \
    --num_train_epochs 1.0 \
    --plot_loss \
    --lora_rank 32 \
    --num_moe 8 \
    --gating Dense \
    --fp16 \
    --remove_unused_columns False \
    --dataset character-llm
```
After I fixed the code like https://github.com/hiyouga/LLaMA-Factory/issues/417:
add the following code in model.py function load_pretrined line 266:
```
   # fix qwen tokenizer
    if tokenizer.bos_token_id is None:
        tokenizer.bos_token = "<|endoftext|>"
    if tokenizer.eos_token_id is None: 
        tokenizer.eos_token = "<|endoftext|>"
``` 

A new error occurs:
```
Traceback (most recent call last):
  File "/home/comp/cscykong/persona/Neeko/train.py", line 19, in <module>
    trainer.train()
  File "/home/comp/cscykong/persona/Neeko/src/trainer.py", line 71, in train
    train_result = self.trainer.train()
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/trainer.py", line 2052, in t
rain
    return inner_training_loop(
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/trainer.py", line 2388, in _
inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/trainer.py", line 3485, in t
raining_step
    loss = self.compute_loss(model, inputs)
File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/trainer.py", line 3532, in c
ompute_loss
    outputs = model(**inputs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, i
n _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, i
n _call_impl
    return forward_call(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line
 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line
 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", lin
e 108, in parallel_apply
    output.reraise()
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.

Original Traceback (most recent call last):
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", lin
e 83, in _worker
    output = module(*input, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, i
n _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, i
n _call_impl
    return forward_call(*args, **kwargs)
  File "/home/comp/cscykong/persona/Neeko/moelora/peft_model.py", line 859, in forward
    return self.base_model(
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, i
n _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, i
n _call_impl
    return forward_call(*args, **kwargs)
  File "/home/comp/cscykong/persona/Neeko/moelora/tuners/moelora.py", line 186, in forward
    return self.model(**kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, i
n _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, i
n _call_impl
    return forward_call(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.
py", line 1167, in forward
    outputs = self.model(
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, i
n _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, i
n _call_impl
    return forward_call(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.
py", line 964, in forward
    layer_outputs = self._gradient_checkpointing_func(
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, i
n _fn
    return fn(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17
, in inner
    return fn(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 482, in
checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in
 apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 261, in
forward
    outputs = run_function(*args)
 File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, i
n _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, i
n _call_impl
    return forward_call(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.
py", line 702, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, i
n _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, i
n _call_impl
    return forward_call(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.
py", line 580, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, i
n _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/comp/cscykong/.conda/envs/persona/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, i
n _call_impl
    return forward_call(*args, **kwargs)
  File "/home/comp/cscykong/persona/Neeko/moelora/tuners/moelora.py", line 711, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: mat1 and mat2 must have the same dtype, but got Float and Half
```

After I add the code below in the forward function, it runs smoothly.
```
    def forward(self, x: torch.Tensor):
        previous_dtype = x.dtype
        batch_size, seq_len, _ = x.size()

        x = x.to(self.weight.dtype)
```
I am now revising the template for qwen to train the model.
Will your repo support deepspeed?

**Comment by PancakeCookie** [comment]
Did you solve the problem? I still get mat1 and mat2 errors and even after solving them in a specific way, the training fails with loss=0, norm=Nan

---
It was a transformers version issue. I solved it by downgrading from the latest version to 4.37.2.

**Comment by yin214** [comment]
> Did you solve the problem? I still get mat1 and mat2 errors and even after solving them in a specific way, the training fails with loss=0, norm=Nan
> 
> It was a transformers version issue. I solved it by downgrading from the latest version to 4.37.2.

Could you let me know your Python version and the versions of other relevant packages? I’m still encountering issues even with transformers 4.37.2.

**Comment by PancakeCookie** [comment]
> > Did you solve the problem? I still get mat1 and mat2 errors and even after solving them in a specific way, the training fails with loss=0, norm=Nan
> > It was a transformers version issue. I solved it by downgrading from the latest version to 4.37.2.
> 
> Could you let me know your Python version and the versions of other relevant packages? I’m still encountering issues even with transformers 4.37.2.

accelerate==0.28.0
bitsandbytes==0.39.0
deepspeed==0.16.4
Jinja2==3.1.5
networkx==3.2.1
ninja==1.11.1.3
nltk==3.9.1
numpy==1.26.4
peft==0.10.0
sentencepiece==0.2.0
tokenizers==0.15.2
torch==2.1.0
transformers==4.37.2
triton==2.1.0

+ neeko.sh
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 8 \

When per_device_train_batch_size becomes 2, learning does not work properly.

**Comment by yin214** [comment]
> > > Did you solve the problem? I still get mat1 and mat2 errors and even after solving them in a specific way, the training fails with loss=0, norm=Nan
> > > It was a transformers version issue. I solved it by downgrading from the latest version to 4.37.2.
> > 
> > 
> > Could you let me know your Python version and the versions of other relevant packages? I’m still encountering issues even with transformers 4.37.2.
> 
> accelerate==0.28.0 bitsandbytes==0.39.0 deepspeed==0.16.4 Jinja2==3.1.5 networkx==3.2.1 ninja==1.11.1.3 nltk==3.9.1 numpy==1.26.4 peft==0.10.0 sentencepiece==0.2.0 tokenizers==0.15.2 torch==2.1.0 transformers==4.37.2 triton==2.1.0
> 
>     * neeko.sh
>       --per_device_train_batch_size 1 
>       --gradient_accumulation_steps 8 \
> 
> 
> When per_device_train_batch_size becomes 2, learning does not work properly.

Thanks for your help!
